name: test
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        perl:
          - "5.36"
          - "5.34"
          - "5.32"
          - "5.30"
          - "5.28"
          - "5.26"
          - "5.24"
          - "5.22"
          - "5.20"
          - "5.18"
          - "5.16"
          - "5.14"
          - "5.12"
        # on macos-latest, only test with latest version of perl.
        # because concurrency of builds on macos-latest is limit and it takes long time.
        include:
          - os: macos-latest
            perl: "5.36"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Perl ${{ matrix.perl }}
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          install-modules-with: cpm

          # develop phase dependencies in cpanfile can't be installed with old perl.
          # so, we only install modules required by CI here.
          install-modules-args: --without-develop
          install-modules: |
            Template
            Pod::HTML2Pod
            Perl::Tidy
            Carp::Always
            Devel::Cover
            Data::Printer
            Carp::Always
            Test::Pod
            Devel::CoverReport

      - name: Test
        run: prove -l -j2 t
        env:
          AUTHOR_TESTING: 1
          PAWS_SILENCE_UNSTABLE_WARNINGS: 1
